# Generated by Django 3.1 on 2020-08-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
