# Generated by Django 3.1 on 2020-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200816_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(),
        ),
    ]
