# Generated by Django 3.1 on 2020-08-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0001_initial'),
        ('news', '0005_auto_20200821_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory.subcategory'),
        ),
    ]
