# Generated by Django 3.1 on 2020-08-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_subcategory_count'),
        ('news', '0006_auto_20200821_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_list', to='subcategory.subcategory'),
        ),
    ]
