# Generated by Django 3.1 on 2020-08-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(max_length=255),
        ),
    ]
