# Generated by Django 3.1 on 2020-08-14 01:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200814_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='phone_number',
            field=models.CharField(default='-', max_length=100, validators=[main.models.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='main',
            name='facebook',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='twitter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='youtube',
            field=models.CharField(max_length=100),
        ),
    ]
